### ISSUE TITLE
Can't select tables with big number of columns

### ISSUE THREAD

**Issue by Nyamhyy** [alex-krash/clickhouse-jdbc-bridge#3]
When selecting tables with a lot of columns you get "414 Request-URI Too Long" error. I understand it's bad idea to select all columns, but sometimes we need to look at all columns for first few rows.

**Comment by alex-krash** [comment]
Thanks for feedback!
I've applied temporary solution in 7d9af92541a202ac3d25fa6c93277fb3757d1f5d. More accurate solution requires ClickHouse fixes, that are not as fast as it could be. Hope that now your columns would fit 24Kb :)
