### ISSUE TITLE
Table and schema reverse  

### ISSUE THREAD

**Issue by LXHING999** [alex-krash/clickhouse-jdbc-bridge#6]
String tableAndSchema = Stream.of(schema, table)
                    .filter(s -> !StringUtil.isBlank(s))
                    .map(s -> quote + s + quote)
                    .collect(Collectors.joining("."));

**Comment by SantyagoSeaman** [comment]
https://github.com/alex-krash/clickhouse-jdbc-bridge/pull/8

**Comment by alex-krash** [comment]
Closed by PR
