### ISSUE TITLE
how to convert .deb file to .rpm file?

### ISSUE THREAD

**Issue by kimlehi** [alex-krash/clickhouse-jdbc-bridge#9]
Hi, the .deb file only work for ubuntu  system, but how can we use it for centos system ?

**Comment by Syrymbatyr** [comment]
m?

**Comment by alex-krash** [comment]
Hello, guys!
Sorry, I've completely missed this question.
Created https://github.com/alex-krash/clickhouse-jdbc-bridge/issues/10, will check next week.
